### ISSUE TITLE
This is not an issue... I just wanted to ask WHICH WALLPAPER IS THAT?

### ISSUE THREAD

**Issue by Prayag2** [KiranWells/ulauncher-nord#1]
Please give us a link to that wallpaper! I'm so sorry I don't know where to ask so I had to open a new Issue... Thanks in advance!

**Comment by KiranWells** [comment]
I am not sure how you can see that much from the preview, but it is from a [nord-wallpapers](https://github.com/pachedearroz/nord-wallpapers/) github, specifically the [Arctic fox](https://github.com/pachedearroz/nord-wallpapers/blob/master/nord-arctic-fox.png). Thanks for the interest!

**Comment by Prayag2** [comment]
Thank you sooo much! I love your theme <3
